-- DELETA ARTISTAS QUE NASCERAM EM 1971
DELETE FROM artista
WHERE data_nascimento between '1971/01/01' and '1971/12/31';

-- DELETA MUSICAS QUE POSSUEM CONTEUDOS IMPROPRIOS
DELETE FROM musica
WHERE impropria = 1;

-- DELETA BANDAS DE ARTISTAS QUE JÁ MORRERAM
DELETE FROM banda
WHERE id_Artista IN
    (SELECT id_Artista
    FROM banda NATURAL JOIN banda_possui_artista NATURAL JOIN artista
    WHERE data_morte IS NOT NULL);

-- DELETA USUARIOS COM SENHAS FRACAS (MENOS QUE 4 CARACTERES)
DELETE FROM usuario
WHERE char_length(senha) < 4;

-- DELETA MUSICA DE NOME 'Stan'
DELETE FROM MUSICA
WHERE nome = 'Stan';